### PR TITLE
Add installation and run script

### PR DESCRIPTION
**Pull request by rodri042**
I think every runner should expose a common way to *install* and *run* inside the VM.
With this files, it will be possible to install any runner with [./install-runner.rb --install gobstones](https://github.com/mumuki/mumuki-offline/pull/2/files)

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Hi @rodri042 !

Since all new runners are developed with the same technology, is it necessary to add this script to all of them? Can't we just assume they are built in rackup at the vm-builder side? 

@faloi please share your thoughts. 

PS: some runners are dockerized. Could this be a problem?

**Comment by rodri042** [comment]
We can assume that and omit the run.sh, but I think the install.sh is very
dependent of the tecnology (ie. in haskell, we need to install cabal).

I'll try someone that uses Docker. My idea in that case is to put a script
to install docker and all the needed programs in install.sh

**Comment by flbulgarelli** [comment]
> We can assume that and omit the run.sh, but I think the install.sh is very
dependent of the tecnology (ie. in haskell, we need to install cabal).

That is the issue. New runners are pure ruby code. Technology dependent configurations are put inside the docker machines the runners use. See for example https://github.com/mumuki/mumuki-hspec-server2

**Comment by flbulgarelli** [comment]
PS: ideally the VM should have haskell installed if we want to use https://github.com/mumuki/mulang in the near future. But that is just a nice to have. Not a priority

**Comment by rodri042** [comment]
Got it! I thought not *all* the runners were written in ruby. In that case
it doesn't make sense to have that logic here.

**Comment by flbulgarelli** [comment]
There are still two runners implemented in Haskell and JS, but they are in migration process and are not mumuki offline yet ;)

**Pull request closed without merging**
